# @package _global_

defaults:
  - model: fire_equality_model
  - datamodule: firetracks_binary
  - trainer: default
  - callbacks: default
  - logger: csv
  - optional scenario: run16

seed: 42

# 
test_after_training: true

# for()
# optimized_metric: val/auc

